In [1]:
import pandas as pd

df = pd.read_excel("data/Muesli Project raw data - group 3.xlsx")

df.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18
0,Index,Order ID,Order Date,Ship Mode,Customer ID,Customer Name,Origin Channel,Country/Region,City,State,Postal Code,Region,Category,Sub-Category,Product ID,Sales,Quantity,Discount,Profit
1,27,CA-2019-121755,2019-01-16 00:00:00,Second Class,EH-13945,Eric Hoffmann,Email,United States,Los Angeles,California,90049,West,Special Projects Muesil,Gluten Free,TEC-AC-10003027,90.57,3,0,11.7741
2,45,CA-2019-118255,2019-03-11 00:00:00,First Class,ON-18715,Odella Nelson,Sales,United States,Eagan,Minnesota,55122,Central,Special Projects Muesil,Gluten Free,TEC-AC-10000171,45.98,2,0,19.7714
3,48,CA-2019-169194,2019-06-20 00:00:00,Standard Class,LH-16900,Lena Hernandez,Email,United States,Dover,Delaware,19901,East,Special Projects Muesil,Gluten Free,TEC-AC-10002167,45,3,0,4.95
4,60,CA-2019-111682,2019-06-17 00:00:00,First Class,TB-21055,Ted Butterfield,Email,United States,Troy,New York,12180,East,Special Projects Muesil,Gluten Free,TEC-AC-10002167,30,2,0,3.3

In [2]:
%store -r df
%store -r df1
%store -r df2
%store -r df2_no_dups
%store -r df3
%store -r df3_no_dups
%store -r df_dur_readytoship_truck
%store -r df_dur_readytoship_truck_standard
%store -r df_dur_readytoship_truck_xpress
%store -r df_no_dups
%store -r df_order_del_time
%store -r df_order_del_time2
%store -r df_order_del_total
%store -r df_prep_dur_ver

In [3]:
df2

            Order ID On Truck Scan Date            Ship Mode
0     CA-2019-125206         2019-01-07              Express
1     CA-2019-160304         2019-01-09  Standard Processing
2     CA-2019-160304         2019-01-09  Standard Processing
3     US-2019-116365         2019-01-09  Standard Processing
4     US-2019-116365         2019-01-09  Standard Processing
...              ...                ...                  ...
5894  CA-2020-143259         2021-01-06  Standard Processing
5895  CA-2020-143259         2021-01-06  Standard Processing
5896  CA-2020-115427         2021-01-06  Standard Processing
5897  CA-2020-115427         2021-01-06  Standard Processing
5898  CA-2020-156720         2021-01-06  Standard Processing

[5899 rows x 3 columns]