In [1]:
import pandas as pd
orders_df = pd.read_excel('../data/Muesli Project raw data - group 3.xlsx', header=1, sheet_name=0)
campaign_data_df = pd.read_excel('../data/Muesli Project raw data - group 3.xlsx', sheet_name=1)
order_process_data_df = pd.read_excel('../data/Muesli Project raw data - group 3.xlsx', sheet_name=2)
interndata_study_df = pd.read_excel('../data/Muesli Project raw data - group 3.xlsx', sheet_name=3)

In [2]:
print('-----Orders-----')
print(orders_df.shape)
display(orders_df.sample(5))

print('-----Campaign Data-----')
print(campaign_data_df.shape)
display(campaign_data_df.sample(5))

print('-----Order Process Data-----')
print(order_process_data_df.shape)
display(order_process_data_df.sample(5))

print('-----InternData Study-----')
print(interndata_study_df.shape)
display(interndata_study_df.sample(5))

-----Orders-----
(9994, 19)

,Index,Order ID,Order Date,Ship Mode,Customer ID,Customer Name,Origin Channel,Country/Region,City,State,Postal Code,Region,Category,Sub-Category,Product ID,Sales,Quantity,Discount,Profit
3918,4688,CA-2019-101987,2019-06-24,Standard Class,HL-15040,Hunter Lopez,Email,United States,Richmond,Indiana,47374.0,Central,Special Projects Muesil,Only Oats,TEC-PH-10001305,440.910,9,0.0,123.4548
2714,4302,CA-2020-129021,2020-08-23,Second Class,PO-18850,Patrick O'Brill,Email,United States,Tallahassee,Florida,32303.0,South,Power Muesli,Nuts and more,OFF-PA-10000141,8.720,5,0.2,2.9430
4527,2828,US-2017-112914,2017-09-25,Standard Class,MT-18070,Michelle Tran,Facebook,United States,Houston,Texas,77041.0,Central,Power Muesli,Power Clean Fibre Boost,OFF-EN-10001509,3.264,2,0.2,1.1016
6389,5399,CA-2019-163202,2019-09-27,Standard Class,BM-11650,Brian Moss,Sales,United States,Lancaster,Ohio,43130.0,East,Power Muesli,Super Fibre Boost,OFF-BI-10002764,2.907,3,0.7,-2.0349
7824,9329,US-2020-130687,2020-09-07,First Class,PF-19225,Phillip Flathmann,Email,United States,Edmonds,Washington,98026.0,West,Power Muesli,Super Mega Protein,OFF-AR-10004260,25.980,1,0.0,7.2744

-----Campaign Data-----
(333, 3)

           Order ID Arrival Scan Date    Customer Name
47   US-2019-148901        2019-05-27  Michael Kennedy
71   CA-2019-154081        2019-06-03          Jim Epp
5    CA-2019-126270        2019-05-06     Art Ferguson
59   CA-2019-119186        2019-05-31    Maurice Satty
146  CA-2019-143406        2019-10-07        Lisa Ryan

-----Order Process Data-----
(5899, 5)

,Row ID,Order ID,Order Date,On Truck Scan Date,Ship Mode
5013,9499,CA-2020-118213,2020-11-05,2020-11-09,Express
4831,5697,CA-2020-126123,2020-10-14,2020-10-21,Standard Processing
1017,6276,US-2019-139087,2019-07-17,2019-07-24,Standard Processing
411,552,CA-2019-136406,2019-04-15,2019-04-19,Standard Processing
2653,9865,CA-2020-113278,2020-01-14,2020-01-22,Standard Processing

-----InternData Study-----
(290, 3)

           Order ID Ready to Ship Date Pickup Date
146  CA-2020-102925         2020-11-10  2020-11-12
212  CA-2020-137022         2020-11-23  2020-11-25
234  CA-2020-120404         2020-11-24  2020-11-25
46   CA-2019-123932         2019-09-12  2019-09-13
199  CA-2020-160416         2020-11-18  2020-11-20